# Use root/example as user/password credentials
version: '3.1'
name: car-rental-app
services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    ports:
      - 27017:27017

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    restart: always
    ports:
      - 61616:61616
      - 8161:8161
    environment:
      password: root
      username: root
